[auth]
redirect_uri="https://telemedicina-kmmkkpp7bbzbvbequqtsld.streamlit.app/"
cookie_secret="1vFzXrj1gHkKJk8hP7CqNn3uBtYzL3EdOg4wRxXbX2M="

[auth_google]
client_id="830471305458-18io31hbau6c0aps91uusa4r981e038n.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"
